[build]
command = "time npm ls bindings prebuild nan node-pre-gyp node-gyp-build --all --json"
functions = "functions"
publish = "publish"

[dev]
command = "npm run dev:netlify"

[[plugins]]
package = "netlify-plugin-cache-nextjs"

[[plugins]]
package = "@netlify/plugin-sitemap"

[plugins.inputs]
baseUrl = "https://explorers.netlify.com"
buildDir = "publish"
exclude = ['./publish/404.html']
